name: calculator-env
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - pywin32
  - cudatoolkit=11.0
  - pytorch==1.7.1
  - torchvision==0.8.2
  - brotli==1.0.9
  - click==8.1.3
  - colorama==0.4.5
  - dash-bootstrap-components==1.2.1
  - dash-core-components==2.0.0
  - dash-html-components==2.0.0
  - dash-table==5.0.0
  - dash==2.6.1
  - flask-compress==1.12
  - flask==2.2.2
  - itsdangerous==2.1.2
  - jinja2==3.1.2
  - markupsafe==2.1.1
  - numpy==1.23.1
  - plotly==5.10.0
  - tenacity==8.0.1
  - werkzeug==2.2.2
  - zipp==3.8.1
  - git
  - pip
  - pip:
    - pillow==7.1.2
    - seaborn
    - importlib-metadata==4.12.0
    - opencv-python==4.6.0.66
    - requests
    - ipython==8.4.0
    - psutil==5.9.1
    - pyyaml
    - scipy==1.4.1